<?php

namespace Plugin\Example\Admin\Hooks;
use Oculus\Engine\Container;
use Oculus\Engine\Plugin;

class Controllerhooks extends Plugin {
	private $script_directory;
	
	public function __construct(Container $app) {
		parent::__construct($app);
		parent::setPlugin('example');
		$this->script_directory = dirname(dirname(__FILE__)) . '/js/';
	}
	
	public function exampleHook($data) {
		$data = $this->language('examplehook', $data);
		
		$data['callback'] = 'Hook replaced callback text.';

		$this->theme->loadjs('example', $data, $this->script_directory);
		
		return $data;
	}

	public function preHook() {
		$data['prehook']  = 'This alert is generated by a pre-hook from the Example plugin.';
		
		$this->theme->loadjs('prehook', $data, $this->script_directory);
		
		return $data;
	}
}